name = "home"
main = "src/worker.js"
compatibility_date = "2026-08-28"

[build]
command = "bun run build"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
BREVO_LIST_ID = "2"
BREVO_SENDER_EMAIL = "dailyquotes@reainsan.com"
BREVO_SENDER_NAME = "Single Life Quotes, by Rea"

[triggers]
crons = ["0 13 * * *"]
