name = "emailworker"
main = "src/worker.js"
compatibility_date = "2026-08-28"

[build]
command = "bun run build"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[triggers]
crons = ["0 13 * * *"]
